// seed/locations.data.js
const s = (str) => str.toLowerCase().replace(/\s+/g, "-");

export const LOCATIONS = [
  {
    name: "Cairo",
    sort: 1,
    cities: [
      "New Cairo",
      "Nasr City",
      "Heliopolis",
      "Maadi",
      "Zamalek",
      "Garden City",
      "Downtown",
      "New Administrative Capital",
      "El Shorouk",
      "Badr City",
      "El Rehab",
      "Ain Shams",
      "El Marg",
      "El Matarya",
      "Other",
    ],
  },
  {
    name: "Giza",
    sort: 2,
    cities: [
      "6th of October City",
      "Sheikh Zayed City",
      "Giza City",
      "Haram",
      "Faisal",
      "Dokki",
      "Mohandessin",
      "Imbaba",
      "Bulaq El Dakrur",
      "Hawamdeya",
      "El Badrashin",
      "Atfeeh",
      "Other",
    ],
  },
  {
    name: "Alexandria",
    sort: 3,
    cities: [
      "Alexandria City",
      "Borg El Arab",
      "Agami",
      "Sidi Gaber",
      "Miami",
      "Smouha",
      "Gleem",
      "Stanley",
      "Montaza",
      "Other",
    ],
  },
  {
    name: "Red Sea",
    cities: [
      "Hurghada",
      "El Gouna",
      "Safaga",
      "Quseir",
      "Marsa Alam",
      "Sahl Hasheesh",
      "Makadi Bay",
      "Soma Bay",
      "Other",
    ],
  },
  {
    name: "South Sinai",
    cities: [
      "Sharm El Sheikh",
      "Dahab",
      "Nuweiba",
      "Taba",
      "St. Catherine",
      "El Tor",
      "Other",
    ],
  },
  {
    name: "North Sinai",
    cities: [
      "El Arish",
      "Rafah",
      "Sheikh Zuweid",
      "Bir El Abd",
      "Nakhl",
      "Other",
    ],
  },
  {
    name: "Luxor",
    cities: [
      "Luxor City (East Bank)",
      "West Bank",
      "Esna",
      "Armant",
      "El Toud",
      "Other",
    ],
  },
  {
    name: "Aswan",
    cities: ["Aswan City", "Edfu", "Kom Ombo", "Daraw", "Abu Simbel", "Other"],
  },
  {
    name: "Qena",
    cities: [
      "Qena City",
      "Nag Hammadi",
      "Qus",
      "Abu Tesht",
      "Deshna",
      "Farshut",
      "Other",
    ],
  },
  {
    name: "Sohag",
    cities: [
      "Sohag City",
      "Akhmim",
      "Girga",
      "Tahta",
      "Tima",
      "El Balyana",
      "Other",
    ],
  },
  {
    name: "Assiut",
    cities: [
      "Assiut City",
      "Manfalut",
      "Abnoub",
      "Dairut",
      "Abu Tig",
      "El Quseyya",
      "Other",
    ],
  },
  {
    name: "Minya",
    cities: [
      "Minya City",
      "Mallawi",
      "Beni Mazar",
      "Samalut",
      "Maghagha",
      "Deir Mawas",
      "Other",
    ],
  },
  {
    name: "Beni Suef",
    cities: [
      "Beni Suef City",
      "El Wasta",
      "Nasser",
      "Ehnasia",
      "Biba",
      "Sumusta El Waqf",
      "Other",
    ],
  },
  {
    name: "Fayoum",
    cities: [
      "Fayoum City",
      "Ibshway",
      "Tamiya",
      "Senuris",
      "Yousef El Seddik",
      "Lake Qarun",
      "Tunis Village",
      "Other",
    ],
  },
  {
    name: "Gharbia",
    cities: [
      "Tanta",
      "El Mahalla El Kubra",
      "Kafr El Zayat",
      "Samanoud",
      "Zefta",
      "Basyoun",
      "Qutour",
      "Other",
    ],
  },
  {
    name: "Dakahlia",
    cities: [
      "Mansoura",
      "Mit Ghamr",
      "Talkha",
      "Aga",
      "Sherbin",
      "Gamasa",
      "Belqas",
      "Other",
    ],
  },
  {
    name: "Sharqia",
    cities: [
      "Zagazig",
      "10th of Ramadan City",
      "Belbeis",
      "Minya El Qamh",
      "Abu Kebir",
      "Kafr Saqr",
      "Fakous",
      "Other",
    ],
  },
  {
    name: "Qalyubia",
    cities: [
      "Banha",
      "Shubra El Kheima",
      "Qalyub",
      "El Obour City",
      "Khusus",
      "Tukh",
      "Qanater El Khairia",
      "Other",
    ],
  },
  {
    name: "Monufia",
    cities: [
      "Shebin El Kom",
      "Menouf",
      "Quesna",
      "Ashmoun",
      "El Bagour",
      "Sadat City",
      "Sers El Lyan",
      "Other",
    ],
  },
  {
    name: "Kafr El Sheikh",
    cities: [
      "Kafr El Sheikh City",
      "Desouk",
      "Baltim",
      "Fuwwah",
      "Sidi Salem",
      "Bella",
      "Metoubes",
      "Other",
    ],
  },
  {
    name: "Beheira",
    cities: [
      "Damanhur",
      "Kafr El Dawwar",
      "Rashid (Rosetta)",
      "Edko",
      "Abu Homs",
      "Housh Eissa",
      "Kom Hamada",
      "Other",
    ],
  },
  {
    name: "Damietta",
    cities: [
      "Damietta City",
      "New Damietta",
      "Ras El Bar",
      "Faraskur",
      "Zarqa",
      "Kafr Saad",
      "Other",
    ],
  },
  {
    name: "Ismailia",
    cities: [
      "Ismailia City",
      "Fayed",
      "El Qantara Gharb",
      "El Qantara Sharq",
      "Tell El Kebir",
      "Abu Suweir",
      "Other",
    ],
  },
  {
    name: "Suez",
    cities: ["Suez City", "Ain Sokhna", "Ataqa", "Arbaeen", "Ganayen", "Other"],
  },
  { name: "Port Said", cities: ["Port Said City", "Port Fuad", "Other"] },
  {
    name: "Matrouh",
    cities: [
      "Marsa Matruh",
      "Siwa",
      "El Alamein",
      "Sidi Abdelrahman",
      "Dabaa",
      "Sidi Barrani",
      "Other",
    ],
  },
  {
    name: "New Valley (El Wadi El Gedid)",
    cities: ["Kharga", "Dakhla (Mut)", "Farafra", "Paris", "Balat", "Other"],
  },
].map((g) => ({
  name: g.name,
  slug: s(g.name),
  sort: g.sort || 0,
  cities: g.cities.map((c) => ({
    name: c,
    slug: s(c),
    popular: [
      "New Cairo",
      "Nasr City",
      "Maadi",
      "6th of October City",
      "Sheikh Zayed City",
      "Alexandria City",
      "Hurghada",
      "Sharm El Sheikh",
    ].includes(c),
  })),
}));
